import "~/styles/globals.css";
import { Inter } from "next/font/google";
import SignInPage from "./_components/SignInPage";
import { SessionProvider } from 'next-auth/react';
import { auth } from "~/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

interface Props {
  children: React.ReactNode
}

export const metadata = {
  title: "Bloggy",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


function TopNav() {
  return (
    <nav className="flex w-full border-b items-center justify-between p-4 text-2xl font-semibold">
      <a href="/">Bloggy</a>
      <SignInPage />
    </nav>
  )
}

async function TaskBar({session}) {
  return (
    <div className="w-full px-4">
      {
        session?.user ? 
        <div className="flex gap-4">
          <button className="bg-green-500 bg-opacity-35 w-max p-2 rounded-lg">
            <a href="/create-post">Create a post</a>
          </button>
          <button className="bg-blue-400 bg-opacity-35 w-max p-2 rounded-lg">
            <a href="/my-posts">My Posts</a>
          </button>
          <button className="bg-pink-500 bg-opacity-35 w-max p-2 rounded-lg">
            <a href="/liked-posts">Liked Posts</a>
          </button>
          {/* <button className="bg-sky-300 bg-opacity-35 w-max p-2 rounded-lg">
            <a href="/saved-posts">Saved Posts</a>
          </button> */}
        </div>
        : <div className="bg-red-700 bg-opacity-55 w-max p-2 rounded-lg">Sign in to create a post</div>
      }
    </div>
  )
}

const RootLayout: React.FC<Props> = async({ children }) => {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col gap-4`}>
        <SessionProvider session={session}>
          <TopNav />
          <TaskBar session={session}/>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}

export default RootLayout;
